name: Create Glue Resources

on:
  workflow_call:
    inputs:
      glue_job_name:
        required: true
        type: string
      s3_bucket_name:
        required: true
        type: string
      iam_role_arn:
        required: true
        type: string

jobs:
  create-glue:
    runs-on: ubuntu-latest

    env:
      GLUE_JOB_NAME: ${{ inputs.glue_job_name }}
      S3_BUCKET_NAME: ${{ inputs.s3_bucket_name }}
      IAM_ROLE_ARN: ${{ inputs.iam_role_arn }}
      GLUE_CONNECTION_NAME: mysql-rds-glue-connection

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Glue Script
        run: |
          aws s3 cp glue/glue_job.py s3://$S3_BUCKET_NAME/glue-scripts/glue_job.py

      - name: Verify Existing Glue Connection
        run: |
          aws glue get-connection \
            --name "$GLUE_CONNECTION_NAME" \
            --query "Connection.[Name,ConnectionType,PhysicalConnectionRequirements]"

      - name: Create Glue Job
        run: |
          aws glue delete-job --job-name "$GLUE_JOB_NAME" || true

          aws glue create-job \
            --name "$GLUE_JOB_NAME" \
            --role "$IAM_ROLE_ARN" \
            --command "Name=glueetl,ScriptLocation=s3://$S3_BUCKET_NAME/glue-scripts/glue_job.py,PythonVersion=3" \
            --glue-version "5.0" \
            --worker-type "G.1X" \
            --number-of-workers 2 \
            --connections Connections=mysql-rds-glue-connection \
            --default-arguments '{"--job-language":"python"}'

      - name: Verify Glue Job Connection
        run: |
          aws glue get-job \
            --job-name "$GLUE_JOB_NAME" \
            --query "Job.Connections"
