name: Create Glue Resources

on:
  workflow_call:
    inputs:
      glue_job_name:
        required: true
        type: string
      s3_bucket_name:
        required: true
        type: string
      iam_role_arn:
        required: true
        type: string
      rds_instance_identifier:
        required: true
        type: string
      db_name:
        required: true
        type: string
      db_username:
        required: true
        type: string

jobs:
  create-glue:
    runs-on: ubuntu-latest

    env:
      GLUE_JOB_NAME: ${{ inputs.glue_job_name }}
      S3_BUCKET_NAME: ${{ inputs.s3_bucket_name }}
      IAM_ROLE_ARN: ${{ inputs.iam_role_arn }}
      RDS_INSTANCE_IDENTIFIER: ${{ inputs.rds_instance_identifier }}
      DB_NAME: ${{ inputs.db_name }}
      DB_USERNAME: ${{ inputs.db_username }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Glue Script
        run: |
          aws s3 cp glue/glue_job.py s3://$S3_BUCKET_NAME/glue-scripts/glue_job.py

      - name: Get RDS Endpoint
        run: |
          ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier "$RDS_INSTANCE_IDENTIFIER" \
            --query "DBInstances[0].Endpoint.Address" \
            --output text)

          echo "RDS_ENDPOINT=$ENDPOINT" >> $GITHUB_ENV

      - name: Check or Create Glue Job
        run: |
          if aws glue get-job --job-name "$GLUE_JOB_NAME" 2>/dev/null; then
            echo "Glue job already exists"
          else
            aws glue create-job \
              --name "$GLUE_JOB_NAME" \
              --role "$IAM_ROLE_ARN" \
              --command "Name=glueetl,ScriptLocation=s3://$S3_BUCKET_NAME/glue-scripts/glue_job.py,PythonVersion=3" \
              --glue-version "4.0" \
              --worker-type "G.1X" \
              --number-of-workers 2 \
              --default-arguments "{
                \"--job-language\":\"python\",
                \"--rds_endpoint\":\"$RDS_ENDPOINT\",
                \"--db_name\":\"$DB_NAME\",
                \"--db_username\":\"$DB_USERNAME\",
                \"--db_password\":\"${{ secrets.DB_PASSWORD }}\"
              }"
          fi
