name: Main Glue Pipeline

on:
  workflow_dispatch:
    inputs:
      redshift_cluster_name:
        required: true
        type: string

      redshift_database_name:
        required: true
        type: string

      glue_job_name:
        required: true
        type: string

      s3_bucket_name:
        required: true
        type: string

      iam_role_arn:
        required: true
        type: string

jobs:
  create-resources:
    uses: ./.github/workflows/create-resources.yml

    with:
      redshift_cluster_name: ${{ inputs.redshift_cluster_name }}
      redshift_database_name: ${{ inputs.redshift_database_name }}
      glue_job_name: ${{ inputs.glue_job_name }}
      s3_bucket_name: ${{ inputs.s3_bucket_name }}
      iam_role_arn: ${{ inputs.iam_role_arn }}

    secrets: inherit

  run-glue-job:
    needs: create-resources

    uses: ./.github/workflows/run-glue-job.yml

    with:
      glue_job_name: ${{ inputs.glue_job_name }}

    secrets: inherit
