name: Main Glue Pipeline

on:
  workflow_dispatch:

jobs:
  create-glue-connection:
    uses: ./.github/workflows/create-glue-connection.yml
    with:
      network_connection_name: mysql-rds-network-connection
      rds_instance_identifier: Glue-Etl
    secrets: inherit

  create-glue-resources:
    needs: create-glue-connection
    uses: ./.github/workflows/create-glue-resources.yml
    with:
      glue_job_name: sales-glue-job
      s3_bucket_name: glue-etl-mlops-pipeline
      iam_role_arn: arn:aws:iam::061578311583:role/glue-etl-role
      rds_instance_identifier: Glue-Etl
      db_name: glue_demo
      db_username: admin
      db_table: glue_demo
      network_connection_name: mysql-rds-network-connection
      script_location: s3://glue-etl-mlops-pipeline/glue-scripts/glue_job.py
      output_path: s3://glue-etl-mlops-pipeline/output/
    secrets: inherit

  run-glue-job:
    needs: create-glue-resources
    uses: ./.github/workflows/run-glue-job.yml
    with:
      glue_job_name: sales-glue-job
    secrets: inherit
