AWSTemplateFormatVersion: "2010-09-09"
Description: Glue Job resource for RDS to S3 extraction
Parameters:
  DbPassword:
    Type: String
    NoEcho: true

Mappings:
  EnvironmentMapping:
    "061578311583":
      Env: "Dev"
      EnvLower: "dev"
      GlueJobName: "sales-glue-job"
      GlueRoleArn: "arn:aws:iam::061578311583:role/glue-etl-role"
      NetworkConnectionName: "mysql-rds-network-connection"
      ScriptLocation: "s3://glue-etl-mlops-pipeline/glue-scripts/glue_job.py"
      OutputPath: "s3://glue-etl-mlops-pipeline/output/"

      SecretIdRds: "new-database-secret"
      DbTable: "glue_demo"


Resources:
  GlueETLJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", GlueJobName]
      Role: !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", GlueRoleArn]
      GlueVersion: "5.0"
      WorkerType: G.1X
      NumberOfWorkers: 2

      Command:
        Name: glueetl
        ScriptLocation: !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", ScriptLocation]
        PythonVersion: "3"

      Connections:
        Connections:
          - !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", NetworkConnectionName]

      DefaultArguments:
        "--job-language": "python"
        "--rds_endpoint": !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", RdsEndpoint]
        "--db_name": !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", DbName]
        "--db_username": !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", DbUsername]
        "--db_password": !Ref DbPassword
        "--db_table": !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", DbTable]
        "--output_path": !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", OutputPath]


Outputs:
  Environment:
    Description: Environment Name
    Value: !FindInMap [EnvironmentMapping, !Ref "AWS::AccountId", Env]

  GlueJobName:
    Description: Glue Job Name
    Value: !Ref GlueETLJob
