AWSTemplateFormatVersion: "2010-09-09"
Description: Glue Job resource for RDS to S3 extraction

Parameters:
  GlueJobName:
    Type: String

  GlueRoleArn:
    Type: String

  NetworkConnectionName:
    Type: String

  ScriptLocation:
    Type: String

  OutputPath:
    Type: String

  RdsEndpoint:
    Type: String

  DbName:
    Type: String

  DbUsername:
    Type: String

  DbPassword:
    Type: String
    NoEcho: true

  DbTable:
    Type: String

Resources:
  GlueETLJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJobName
      Role: !Ref GlueRoleArn
      GlueVersion: "5.0"
      WorkerType: G.1X
      NumberOfWorkers: 2

      Command:
        Name: glueetl
        ScriptLocation: !Ref ScriptLocation
        PythonVersion: "3"

      Connections:
        Connections:
          - !Ref NetworkConnectionName

      DefaultArguments:
        "--job-language": "python"
        "--rds_endpoint": !Ref RdsEndpoint
        "--db_name": !Ref DbName
        "--db_username": !Ref DbUsername
        "--db_password": !Ref DbPassword
        "--db_table": !Ref DbTable
        "--output_path": !Ref OutputPath

Outputs:
  GlueJobName:
    Description: Glue Job Name
    Value: !Ref GlueETLJob
