name: Run Glue Job SQL

on:
  workflow_call:
    inputs:
      glue_job_name:
        required: true
        type: string

jobs:
  run-glue:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ----------------------------------------------------
      # Run Glue Job
      # ----------------------------------------------------

      - name: Start Glue Job
        run: |

          aws glue start-job-run \
            --job-name "${{ inputs.glue_job_name }}"
