name: Run Glue Job

on:
  workflow_call:
    inputs:
      glue_job_name:
        required: true
        type: string
      github_role_arn:
        required: true
        type: string

jobs:
  run-glue:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:  ${{ inputs.github_role_arn }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Start Glue Job
        run: |
          aws glue start-job-run \
            --job-name "${{ inputs.glue_job_name }}"
